---
new_page_extension: md
auto_deploy: false
admin_path: https://11ty-forestry-demo.now.sh/cms
webhook_url: https://api.zeit.co/v1/integrations/deploy/QmQCWKhaD5KTNAF9xWM1uu96EDibWTqnJbJkNNt5pAge9S/bpwy8sLKLL
sections:
- type: heading
  label: Content
- type: directory
  path: src/posts
  label: Posts
  create: documents
  match: "*.md"
  templates:
  - post
- type: heading
  label: Globals
- type: document
  path: src/_data/tokens.json
  label: Theme settings
upload_dir: src/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - ELEVENTY_ENV=staging
  preview_output_directory: src/dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv/src"
  instant_preview_command: npm run develop
